/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import app.domain.AppStates;
import app.helpers.ArtistFactory;
import app.helpers.ComboItem;
import business.AccountService;
import business.ArtistService;
import domain.Account;
import domain.Artist;
import domain.exceptions.TicketNotFoundException;
import domain.exceptions.ValidationFaliedException;
import java.util.UUID;
import javax.swing.JOptionPane;

/**
 *
 * @author priva_000
 */
public class AuthenticationPanel extends javax.swing.JPanel {

    private final AccountService accountService = new AccountService();
    private final ArtistService artistService = new ArtistService();

    private MainFrame mainFrame;

    /**
     * Creates new form AuthenticationPanel
     */
    public AuthenticationPanel() {
        initComponents();

        for (Artist artist : this.artistService.findAll()) {
            this.ddlListOfArtists.addItem(ArtistFactory.buildComboxItem(artist));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnAuthenticate = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        lblArtist = new javax.swing.JLabel();
        ddlListOfArtists = new javax.swing.JComboBox();
        lblLogoImage = new javax.swing.JLabel();

        lblUsername.setText("Username");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        txtPassword.setText("997483276");

        btnAuthenticate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/button.png"))); // NOI18N
        btnAuthenticate.setText("Sign in");
        btnAuthenticate.setContentAreaFilled(false);
        btnAuthenticate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAuthenticate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthenticateActionPerformed(evt);
            }
        });

        lblPassword.setText("Ticket code");

        lblInfo.setFont(lblInfo.getFont().deriveFont(lblInfo.getFont().getSize()-5f));
        lblInfo.setText("<html>\n\tPlease enter a username, your ticket code and your favorite artist\n</html>");

        lblArtist.setText("Artist");

        ddlListOfArtists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddlListOfArtistsActionPerformed(evt);
            }
        });

        lblLogoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/transparent-logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogoImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInfo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnAuthenticate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(ddlListOfArtists, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblArtist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ddlListOfArtists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAuthenticate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAuthenticateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthenticateActionPerformed
        try {
            String username = txtUsername.getText();
            if (username.length() == 0) {
                throw new ValidationFaliedException("Username can not be empty");
            }

            String password = txtPassword.getText();
            if (password.length() == 0) {
                throw new ValidationFaliedException("Ticket code can not be empty");
            }

            ComboItem selectedItem = (ComboItem) ddlListOfArtists.getSelectedItem();

            Account account = new Account(UUID.randomUUID(), username, password, UUID.fromString(selectedItem.getValue()));

            accountService.add(account);

            AppState.getInstance().setAccount(account);
            AppState.getInstance().setState(AppStates.PLAYING);
        } catch (ValidationFaliedException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (TicketNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnAuthenticateActionPerformed

    private void ddlListOfArtistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddlListOfArtistsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddlListOfArtistsActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    public void setMainFrame(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuthenticate;
    private javax.swing.JComboBox ddlListOfArtists;
    private javax.swing.JLabel lblArtist;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblLogoImage;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
