/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

/**
 *
 * @author priva_000
 */
public class GamePanel extends javax.swing.JPanel {

    private static final int EMPTY_BORDER_SIZE = 5;
    private MainFrame mainFrame;

    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
    }

    public void initializeGame() {
        greenfootStandaloneScenarioViewer1.run();
    }

    public void setMainFrame(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        greenfootStandaloneScenarioViewer1 = new greenfooter.GreenfootStandaloneScenarioViewer();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        greenfootStandaloneScenarioViewer1.setBackground(new java.awt.Color(204, 255, 51));

        javax.swing.GroupLayout greenfootStandaloneScenarioViewer1Layout = new javax.swing.GroupLayout(greenfootStandaloneScenarioViewer1);
        greenfootStandaloneScenarioViewer1.setLayout(greenfootStandaloneScenarioViewer1Layout);
        greenfootStandaloneScenarioViewer1Layout.setHorizontalGroup(
            greenfootStandaloneScenarioViewer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        greenfootStandaloneScenarioViewer1Layout.setVerticalGroup(
            greenfootStandaloneScenarioViewer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        add(greenfootStandaloneScenarioViewer1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

    }//GEN-LAST:event_formComponentShown

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        greenfootStandaloneScenarioViewer1.stop();
    }//GEN-LAST:event_formComponentHidden


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private greenfooter.GreenfootStandaloneScenarioViewer greenfootStandaloneScenarioViewer1;
    // End of variables declaration//GEN-END:variables
}
