/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import app.domain.AppStates;

/**
 *
 * @author priva_000
 */
public class GameLostPanel extends javax.swing.JPanel {

    /**
     * Creates new form GameLostPanel
     */
    public GameLostPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLostHeader = new javax.swing.JLabel();
        lblScoreText = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        panelButtons = new javax.swing.JPanel();
        btnPlayAgain = new javax.swing.JButton();
        btnHighscore = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();

        lblLostHeader.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblLostHeader.setText("You lost!");

        lblScoreText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblScoreText.setText("You finished the game with a score of: ");

        lblScore.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblScore.setText("0");

        panelButtons.setLayout(new java.awt.BorderLayout());

        btnPlayAgain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/button.png"))); // NOI18N
        btnPlayAgain.setText("Play again");
        btnPlayAgain.setContentAreaFilled(false);
        btnPlayAgain.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlayAgain.setMargin(new java.awt.Insets(0, 14, 2, 14));
        btnPlayAgain.setPreferredSize(new java.awt.Dimension(333, 70));
        btnPlayAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAgainActionPerformed(evt);
            }
        });
        panelButtons.add(btnPlayAgain, java.awt.BorderLayout.PAGE_END);

        btnHighscore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/button.png"))); // NOI18N
        btnHighscore.setText("Highscore");
        btnHighscore.setContentAreaFilled(false);
        btnHighscore.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHighscore.setPreferredSize(new java.awt.Dimension(333, 70));
        btnHighscore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHighscoreActionPerformed(evt);
            }
        });
        panelButtons.add(btnHighscore, java.awt.BorderLayout.CENTER);

        btnSignOut.setText("Sign out");
        btnSignOut.setContentAreaFilled(false);
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLostHeader)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblScoreText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblScore)))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnSignOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLostHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblScoreText)
                    .addComponent(lblScore))
                .addGap(72, 72, 72)
                .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(btnSignOut)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHighscoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighscoreActionPerformed
        AppState.getInstance().setState(AppStates.HIGHSCORE);
    }//GEN-LAST:event_btnHighscoreActionPerformed

    private void btnPlayAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAgainActionPerformed
        AppState.getInstance().setState(AppStates.PLAYING);
    }//GEN-LAST:event_btnPlayAgainActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        AppState.getInstance().setAccount(null);
        AppState.getInstance().setState(AppStates.AUTHENTICATE);
    }//GEN-LAST:event_btnSignOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHighscore;
    private javax.swing.JButton btnPlayAgain;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JLabel lblLostHeader;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblScoreText;
    private javax.swing.JPanel panelButtons;
    // End of variables declaration//GEN-END:variables

    void setScore(int score) {
        lblScore.setText(String.valueOf(score));
    }
}
