/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import app.domain.AppStates;
import game.GameResult;
import java.awt.CardLayout;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author priva_000
 */
public class MainFrame extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        AppState.getInstance().addObserver(this);

        authenticationPanel.setMainFrame(this);
        gamePanel.setMainFrame(this);
    }

    void beginGame() {
        CardLayout cardLayout = (CardLayout) this.mainPanel.getLayout();
        cardLayout.show(this.mainPanel, "gameCard");
        gamePanel.initializeGame();
    }

    @Override
    public void update(Observable o, Object o1) {
        AppStates currentState = AppState.getInstance().getState();

        CardLayout cardLayout = (CardLayout) this.mainPanel.getLayout();

        switch (currentState) {
            case PLAYING:
                beginGame();
                break;
            case AUTHENTICATE:
                cardLayout.show(this.mainPanel, "authenticationCard");
                break;
            case LOST:
                GameResult gameResult = (GameResult)o1;
                cardLayout.show(this.mainPanel, "gameLostCard");
                this.gameLostPanel.setScore(gameResult.getScore());
                break;
            case HIGHSCORE:
                cardLayout.show(this.mainPanel, "highscoreCard");
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        authenticationPanel = new app.AuthenticationPanel();
        gamePanel = new app.GamePanel();
        gameLostPanel = new app.GameLostPanel();
        highscorePanel = new app.HighscorePanel();
        footerNavigationPanel = new app.FooterNavigationPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(320, 568));
        setResizable(false);

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.CardLayout());

        authenticationPanel.setName("authenticationPanel"); // NOI18N
        mainPanel.add(authenticationPanel, "authenticationCard");

        gamePanel.setName("gamePanel"); // NOI18N
        mainPanel.add(gamePanel, "gameCard");

        gameLostPanel.setName("gameLostPanel"); // NOI18N
        mainPanel.add(gameLostPanel, "gameLostCard");

        highscorePanel.setName("highscorePanel"); // NOI18N
        mainPanel.add(highscorePanel, "highscoreCard");

        footerNavigationPanel.setName("footerNavigationPanel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, Short.MAX_VALUE)
            .addComponent(footerNavigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footerNavigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.AuthenticationPanel authenticationPanel;
    private app.FooterNavigationPanel footerNavigationPanel;
    private app.GameLostPanel gameLostPanel;
    private app.GamePanel gamePanel;
    private app.HighscorePanel highscorePanel;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

}
